INSERT INTO tb_game_list (name) VALUES ('Todos os Jogos');
INSERT INTO tb_game_list (name) VALUES ('Meus Favoritos');

INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('Street Fighter 6', 4.6, 2023, 'Role-playing (RPG) e Tiro', 'PlayStation 4|5,Xbox Series S|X, Arcade e Windows', 'https://image.api.playstation.com/vulcan/ap/rnd/202211/1407/XFU0aPBvtm3W2od1ZvhByAOv.png', '[Wikipedia] - Street Fighter 6 é um jogo de luta desenvolvido e publicado pela Capcom. Anunciado em fevereiro de 2022, é o sétimo título principal da franquia Street Fighter.', '[Wikipedia] - Desenvolvido no RE Engine, o Street Fighter 6 oferece suporte para reprodução entre plataformas e código de rede de reversão. Oferece três modos de jogo abrangentes e três opções de controle. O jogo também apresenta um sistema de comentários em tempo real, proporcionando uma sensação de estilo de torneio e a opção de torcer pelo jogador.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.3, 2018, 'Role-playing (RPG) e Aventura', 'PlayStation 4, Xbox One, Google Stadia e Windows', 'https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png', '[Wikipedia] - Red Dead Redemption 2 é um jogo de ação e aventura desenvolvido e publicado pela Rockstar Games. O jogo é a terceira entrada na série Red Dead.', '[Wikipedia] - A história se passa em uma representação fictícia dos Estados Unidos em 1899 e segue as façanhas de Arthur Morgan, um fora da lei e membro da gangue Van der Linde, que deve lidar com o declínio do Velho Oeste enquanto tenta sobreviver contra as forças do governo, gangues rivais e outros adversários. O jogo é apresentado por meio de perspectivas de primeira e terceira pessoa, e o jogador pode vagar livremente em seu mundo aberto interativo.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.6, 2014, 'Role-playing (RPG) e Aventura', 'PlayStation 4|5, Nintendo Switch, Xbox One, Xbox Series X|S e Windows', 'https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/kh4MUIuMmHlktOHar3lVl6rY.png', '[Wikipedia] - The Witcher 3: Wild Hunt é um RPG de ação desenvolvido e publicado pela CD Projekt. É a sequência do jogo de 2011 The Witcher 2: Assassins of Kings e o terceiro jogo da série de videogames The Witcher.', '[Wikipedia] - O jogo se passa em um mundo de fantasia fictício baseado na mitologia eslava. Os jogadores controlam Geralt of Rivia, um matador de monstros de aluguel conhecido como Witcher, e procuram por sua filha adotiva, que está fugindo da Wild Hunt sobrenatural. Os jogadores lutam contra os muitos perigos do jogo com armas e magia, interagem com personagens e completam missões.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('Resident Evil 4', 4.0, 2023, 'Terror, Sobrevivência, Ação e Aventura', 'PlayStation 4|5, Xbox Series X|S e Steam', 'https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/EVWyZD63pahuh95eKloFaJuC.png', '[Wikipedia] - Resident Evil 4 é um jogo eletrônico de survival horror e tiro em terceira pessoa desenvolvido e publicado pela Capcom é o sexto jogo principal da franquia Resident Evil.', '[Wikipedia] - A história segue o agente especial Leon S. Kennedy, que é enviado em uma missão para resgatar a filha do presidente dos Estados Unidos, Ashley Graham, que foi sequestrada por um culto religioso em uma parte rural da Espanha. Leon luta contra hordas de inimigos infectados por um parasita controlador de mentes e se reúne com a espiã Ada Wong.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('Final Fantasy XVI', 4.4, 2023, 'Role-playing (RPG), Luta e Aventura', 'PlayStation 5', 'https://image.api.playstation.com/vulcan/ap/rnd/202210/2407/T7XXHmYlFA3sUGYGp8KT3jbU.png', '[Wikipedia] - Final Fantasy XVI é um jogo eletrônico de RPG de ação desenvolvido e publicado pela Square Enix, é o décimo sexto título principal da série Final Fantasy.', '[Wikipedia] - Final Fantasy XVI se passa no mundo ficcional de Valisthea, onde a população vive com conforto graças a enormes montanhas de cristal chamadas de Cristais-Máter. O mundo é controlado por seis países: o Grão-Ducado de Rosaria, o Sacro Império de Sanbreque, o Reino de Waloed, a República de Dhalmekia, o Reino de Ferro e o Domínio Cristalino. Um importante aspecto do mundo são os Eikons, monstros convocáveis controlados ou manifestados por humanos chamados de Dominante.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('Assassin''s Creed Mirage', 0, 2023, 'Furtividade, Luta, Ação e Aventura', 'PlayStation 4|5, Xbox One, Xbox Series X|S e Windows', 'https://image.api.playstation.com/vulcan/ap/rnd/202208/1718/NFf86jgU4AeVYgJBEoEKBpxW.jpg', '[Wikipedia] - Assassin''s Creed Mirage é um futuro jogo desenvolvido e publicado pela Ubisoft. Será a décima terceira parcela principal da série Assassin''s Creed.', '[Wikipedia] - Situado principalmente na Bagdá do século IX durante a Era de Ouro Islâmica, o jogo seguirá Basim Ibn Ishaq (um personagem introduzido pela primeira vez em Valhalla e sua transição de ladrão de rua para membro de pleno direito da irmandade dos assassinos) que luta pela paz e liberdade, contra a Ordem dos Templários, que desejam a paz através do controle.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('God of War Ragnarök', 4.7, 2022, 'Role-playing (RPG), Luta, Ação e Aventura', 'PlayStation 4|5', 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/EUg935xYj1xnRS8jkKAapzCp.png', '[Wikipedia] - God of War Ragnarök é um jogo eletrônico de ação e aventura desenvolvido pela Santa Monica Studio e publicado pela Sony Interactive Entertainment. É o nono título da série God of War, o nono em ordem cronológica.', '[Wikipedia] - Vagamente baseado na mitologia nórdica, o jogo se passa na antiga Escandinávia e apresenta os protagonistas Kratos e seu filho Atreus. Servindo como o final da era nórdica da série, o jogo dá início ao Ragnarök, uma série de eventos que trazem o fim dos tempos e retrata a morte de alguns dos deuses nórdicos, que foi predito no jogo anterior após Kratos ter matado o deus Æsir Baldur.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('Horizon Forbidden West', 4.4, 2022, 'Luta e Aventura', 'PlayStation 4|5', 'https://image.api.playstation.com/vulcan/ap/rnd/202107/3100/ki0STHGAkIF06Q4AU8Ow4OkV.png', '[Wikipedia] - Horizon Forbidden West é um jogo eletrônico de RPG de ação desenvolvido pela Guerrilla Games e publicado pela Sony Interactive Entertainment. É a sequência de Horizon Zero Dawn, sendo ambientada em um mundo aberto pós-apocalíptico.', '[Wikipedia] - Horizon Forbidden West é um jogo eletrônico de RPG de ação com uma perspectiva em terceira pessoa. Os jogadores controlam Aloy, uma caçadora em um mundo governado por máquinas. O jogo apresenta um mundo aberto ambientado numa Califórnia pós-apocalíptica. Os locais apresentados no trailer de anúncio do jogo incluem uma São Francisco em ruínas e Vale de Yosemite.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('Forza Horizon 5', 3.8, 2021, 'Corrida, Ação e Aventura', 'Xbox One, Xbox Series X|S, Xbox Cloud Gaming, Android e Windows', 'https://store-images.s-microsoft.com/image/apps.49800.13718773309227929.bebdcc0e-1ed5-4778-8732-f4ef65a2f445.9ac09d39-064d-466c-81ca-2f1b6f0b95c5', '[Wikipedia] - Forza Horizon 5 é um jogo eletrônico de corrida desenvolvido pela Playground Games e publicado pela Xbox Game Studios. É o décimo segundo título principal da franquia Forza.', '[Wikipedia] - Forza Horizon 5 é um jogo eletrônico de corrida ambientado em um ambiente de mundo aberto que se passa em uma representação ficcional do México. O jogo tem o maior mapa de toda a série Forza Horizon, sendo 50% maior do que o de Forza Horizon 4, além de também ter o ponto mais alto da série Horizon.');
INSERT INTO tb_game (title, score, game_year, gender, platforms, img_url, short_description, long_description) VALUES ('Hitman 3', 4.3, 2021, 'Furtividade, Tiro, Ação e Aventura', 'PlayStation 4|5, Nintendo Switch, Xbox One, Xbox Series X|S, Google Stadia e Windows', 'https://image.api.playstation.com/vulcan/ap/rnd/202301/2315/AV5D2dPmPZL9CT3IdveGCGJZ.jpg', '[Wikipedia] - Hitman 3 é um jogo eletrônico de furtividade desenvolvido e publicado pela IO Interactive. É o oitavo título principal da série Hitman.', '[Wikipedia] - Hitman 3 é um jogo furtivo jogado numa perspetiva de terceira pessoa. Os jogadores assumem o papel do Agente 47 explorando vários locais ao redor do mundo com o objetivo de assassinar alvos contratados.Hitman 3 conclui a historia da trilogia, com o Agente 47 e os seus aliados a perseguir os lideres da Providence, uma organização secreta que controla os negócios mundiais.');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 6, 5);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 7, 6);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 8, 7);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 9, 8);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 10, 9);
